version: '3.1'

services:

  nginx:
    image: nginx:1.17.1
    container_name: nginx
    ports:
      - 3000:3000
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=localhost

  mongo:
    image: mongo:4.0.10
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  api:
    image: node:10.16.0-alpine
    restart: always
    container_name: api
    ports:
      - 4000:4000
    volumes:
      - ./backend:/src
    working_dir: /src
    depends_on:
      - mongo
    command: [./wait-for-mongo.sh, npm, start]

