version: '3.1'

services:

  mongo:
    image: mongo:4.0.10
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  api:
    image: node:10.16.0-alpine
    restart: always
    container_name: api
    ports:
      - 4000:4000
    volumes:
      - ./backend:/src
    working_dir: /src
    depends_on:
      - mongo
    command: [./wait-for-mongo.sh, npm, start]

